# -*- coding: utf-8 -*-
{
    "name": "frepple",
    "version": "13.0.6.7.1",
    "category": "Manufacturing",
    "summary": "Advanced planning and scheduling",
    "author": "frePPLe, brain-tec AG",
    "website": "https://frepple.com",
    "license": "AGPL-3",
    "description": "Connector to frePPLe - finite capacity planning and scheduling",
    "depends": [
        "product",
        "purchase",
        "sale",
        "resource",
        "mrp",
        'stock',
        "uom",
    ],
    "external_dependencies": {"python": ["jwt"]},
    "data": [
        "views/frepple_data.xml",
        "views/res_company.xml",
        "views/res_config_settings_views.xml",
        "security/frepple_security.xml",
        "data/mrp_routing.xml",
    ],
    "demo": ["data/demo.xml"],
    "test": [],
    "installable": True,
    "auto_install": False,
}
