# -*- coding: utf-8 -*-
{
    "name": "frepple",
    "version": "19.0.0.0",
    "category": "Manufacturing",
    "summary": "Advanced planning and scheduling",
    "author": "frePPLe",
    "website": "https://frepple.com",
    "license": "Other OSI approved licence",
    "description": "Connector to frePPLe - finite capacity planning and scheduling",
    "depends": ["base", "product", "purchase", "sale", "resource", "mrp", "web"],
    "data": [
        "security/frepple_security.xml",
        "security/ir.model.access.csv",
        "views/frepple_recommendation.xml",
        "views/frepple_data.xml",
        "views/res_config_settings_views.xml",
        "views/mrp_bom.xml",
        "views/mrp_skill.xml",
        "views/mrp_workcenter_skill.xml",
        "views/mrp_workcenter_inherit.xml",
        "views/mrp_secondary_workcenter.xml",
        "views/mrp_routing_workcenter_inherit.xml",
        "views/mrp_workorder_inherit.xml",
        "views/mrp_workorder_secondary_workcenter.xml",
        "views/product_supplierinfo_inherit.xml",
        "views/sale_views.xml",
        "views/quote_views.xml",
    ],
    "test": [],
    "installable": True,
    "auto_install": False,
    "application": True,
    "assets": {
        "web.assets_backend": [
            "frepple/static/src/js/frepple.js",
            "frepple/static/src/js/html_tooltip_widget.js",
            "frepple/static/src/js/frepple_recommendation_banner.js",
            "frepple/static/src/xml/frepple_recommendation_banner.xml",
            "frepple/static/src/css/frepple_empty_recommendations.css",
        ],
    },
    "price": 0,
    "currency": "EUR",
    "images": ["static/description/images/frepple_animation.gif"],
}
