from . import res_company
from . import res_config_settings
from . import res_partner
from . import sale_order_line
from . import product_product
from . import stock_location
from . import stock_move_line
from . import mrp_skill
from . import mrp_workcenter_inherit
from . import mrp_routing_workcenter_inherit
from . import mrp_workcenter_skill
from . import mrp_production
